### ISSUE TITLE
fviz_silhouette, legend

### ISSUE THREAD

**Issue by fbenedett** [kassambara/factoextra#95] opened 2019-07-16 08:09 UTC
Hello,

I am trying to change the legend when printing the silhouette but I am unable to do it.
At the moment the best I can do is the following:

```
fviz_silhouette(sil)+
scale_fill_discrete(labels=levels(list_of_names)
```

But unfortunately, instead of replacing the names in the legend, it makes a strange duplicate.
You can see the result in the image.   Is there a way to remove the legend that shows the numbers?
![silhouette_named_Monocytes_recluster](https://user-images.githubusercontent.com/11632090/61277067-a624f280-a7b1-11e9-909f-3879d8651b54.png)

**Comment by ederisoud** [comment] 2020-12-18 09:41
Hello

I have the same issue with fviz_pca_ind function. 
Did you find a solution? 

Thank you

Emilie

**Comment by fbenedett** [comment] 2020-12-18 09:47
I did.  I asked in stackoverflow and I got an answer.  I am not sure if it does help in your case, but look here (and if you can upvote :)
https://stackoverflow.com/questions/57428431/how-can-i-change-the-legend-in-fviz-silhouette

**Comment by ederisoud** [comment] 2020-12-18 09:56
Not at all :( I am desperate...
Thank you for the reply in any case 

Never mind, I will remove the wrong legend manually. I've already spent too much time looking for a solution to this problem.

**Comment by kassambara** [comment] 2020-12-18 10:15
Hi, the barplot is both colored and filled by cluster, so you need to change the labels of both color and fill aesthetics, as follow:

``` r
library(factoextra)
#> Le chargement a nécessité le package : ggplot2
#> Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
library(cluster)
set.seed(123)
data("iris")
iris.scaled <- scale(iris[, -5])
# K-means clustering

km.res <- kmeans(iris.scaled, 3, nstart = 2)
# Visualize silhouhette information
# Default plot
sil <- silhouette(km.res$cluster, dist(iris.scaled))
fviz_silhouette(sil)
#>   cluster size ave.sil.width
#> 1       1   50          0.64
#> 2       2   53          0.39
#> 3       3   47          0.35
```

![](https://i.imgur.com/lxfEyVY.png)

``` r

# CHANG LABELS: You need to do this for both color and fill
fviz_silhouette(sil)+
  scale_fill_discrete(labels=c("a","b","c")) +
  scale_color_discrete(labels = c("a","b","c"))
#>   cluster size ave.sil.width
#> 1       1   50          0.64
#> 2       2   53          0.39
#> 3       3   47          0.35
```

![](https://i.imgur.com/FsZnuAl.png)

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Please let me know if this solution is ok, so that we can close this issue.

**Comment by ederisoud** [comment] 2020-12-18 11:04
Hello

I used this post because I have the same problem but with the fviz_pca_ind function. 
This solution is not working in my case. 
Do you have another possibility for the function fviz_pca_ind? 

Thank you

Emilie

**Comment by kassambara** [comment] 2020-12-18 11:22
Would you please provide a reproducible script of the problem (as above) so that we can help eficiently?

**Comment by ederisoud** [comment] 2020-12-18 13:57
Ok so I have this script:
```
fviz_pca_ind(pca,
             geom.ind = "point", # Montre les points seulement (mais pas le "ICMxt")
             axes=c(1,2),
             col.ind = new$group, # colorer by groups
             #palette = c("green", "black","blue","pink"),
             addEllipses = TRUE, # Ellipses de concentration
             ellipse.type = "confidence",
             legend.title = "Groups"
)
```
Which gave me this PCA graph of individus:
![image](https://user-images.githubusercontent.com/58744268/102622191-f8a1d580-4140-11eb-80ec-db316c334ff7.png)


But I wanted to rename legend labels. I found this script on internet to do that:
```
fviz_pca_ind(pca,
             geom.ind = "point", # Montre les points seulement (mais pas le "ICMxt")
             axes=c(1,2),
             col.ind = new$group, # colorer by groups
             #palette = c("green", "black","blue","pink"),
             addEllipses = TRUE, # Ellipses de concentration
             ellipse.type = "confidence",
             legend.title = "Groups"
)+
        scale_color_manual(labels=c("a","b","c","d"),
                           values=c("green", "black","blue","pink"))+
        guides(colour=guide_legend(show=FALSE))
```
And I obtain this image:
![image](https://user-images.githubusercontent.com/58744268/102622128-e58f0580-4140-11eb-9ba6-72a74aa599aa.png)

But I do not know why there are two legends. I would like to keep only the 2nd. 
That's why I asked the author of this post if he had found the solution for his graphic. I figured the problem must be the same one.

Thank you for your answer. 

Emilie

**Comment by kassambara** [comment] 2020-12-18 23:16
@ederisoud there is two options:

**Option 1 - Prepare your data with the desired labels before the analysis**

``` r
suppressPackageStartupMessages(library(factoextra))

# Data Preparation
# Re-label the grouping variable (here, Species)
# with the desired labels: c("a", "b", "c")
iris2 <- iris
iris2$Species <- factor(
  iris2$Species,
  levels = c("setosa", "versicolor", "virginica"),
  labels = c("a", "b", "c")
  )

# PCA
pca <- prcomp(iris2[, -5],  scale = TRUE)
fviz_pca_ind(pca,
             geom.ind = "point",
             col.ind = iris2$Species,
             palette = c("green", "black","blue","pink"),
             addEllipses = TRUE,
             ellipse.type = "confidence",
             legend.title = "Groups"
)
```

![](https://i.imgur.com/nxGOtjz.png)


**Option 2 - Create the plot then change the labels**. This is a little bit tricky

``` r
suppressPackageStartupMessages(library(factoextra))

# Default plot
data(iris)
pca <- prcomp(iris[, -5],  scale = TRUE)
myplot <- fviz_pca_ind(pca,
             geom.ind = "point",
             col.ind = iris$Species,
             palette = c("green", "black","blue","pink"),
             addEllipses = TRUE,
             ellipse.type = "confidence",
             legend.title = "Groups"
             )
myplot
```

![](https://i.imgur.com/s1y9LhC.png)

``` r


# Changing legend labels
# Using ggplot verbs
myplot +
  # for points colors in the legend
  scale_color_manual(labels=c("a","b","c"), values = c("green", "black","blue","pink")) +
  # for point shape in the legend
  scale_shape_discrete(labels=c("a","b","c")) + 
  # for ellipse fill color
  scale_fill_manual(labels=c("a","b","c"), values = c("green", "black","blue","pink")) 
#> Scale for 'colour' is already present. Adding another scale for 'colour',
#> which will replace the existing scale.
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
```

![](https://i.imgur.com/4qdG6cV.png)

<sup>Created on 2020-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by ederisoud** [comment] 2020-12-22 16:13
Hello thank you for this answer. 

I will try this solution and let you know 

Thank you

Emilie

**Closed** 2020-12-22 18:00 UTC
